image: "rust:latest"

stages:
  - build
  - test
  - build_targets

before_script:
  - apt-get update -yqq
  - apt-get install -yqq --no-install-recommends build-essential

build-debug:
  stage: build
  script:
    - rustc --version && cargo --version # Print version info for debugging
    - cargo build --verbose
  artifacts:
    paths:
      - target/x86_64-unknown-linux-gnu/debug/knowmark-server
  cache:
    key:
      files:
        - Cargo.toml
    paths:
      - target/debug

test-debug:
  stage: test
  dependencies:
    - build-debug
  services:
    - mongo:latest
  script:
    - sudo systemctl start mongod
    - RUST_LOG=debug cargo test --workspace --verbose

build-linux:
  stage: build_targets
  script:
    - rustup target add x86_64-unknown-linux-gnu
    - cargo build --release --target x86_64-unknown-linux-gnu --verbose
  artifacts:
    paths:
      - target/x86_64-unknown-linux-gnu/debug/knowmark-server

build-windows:
  stage: build_targets
  script:
    - rustup target add x86_64-pc-windows-msvc
    - cargo build --release --target x86_64-pc-windows-msvc --verbose
  artifacts:
    paths:
      - target/x86_64-pc-windows-msvc/debug/knowmark-server

build-openbsd:
  stage: build_targets
  script:
    - rustup target add x86_64-unknown-openbsd
    - cargo build --release --target x86_64-unknown-openbsd --verbose
  artifacts:
    paths:
      - target/x86_64-unknown-openbsd/debug/knowmark-server

build-apple-x64:
  stage: build_targets
  script:
    - rustup target add x86_64-apple-darwin
    - cargo build --release --target x86_64-apple-darwin --verbose
  artifacts:
    paths:
      - target/x86_64-apple-darwin/debug/knowmark-server

build-apple-arm:
  stage: build_targets
  script:
    - rustup target add aarch64-apple-darwin
    - cargo build --release --target aarch64-apple-darwin --verbose
  artifacts:
    paths:
      - target/aarch64-apple-darwin/debug/knowmark-server
