image: "rust:latest"

stages:
  - build
  - test
  - build_targets

before_script:
  - wget -qO - https://pgp.mongodb.com/server-6.0.asc | apt-key add -
  - echo "deb [ arch=amd64,arm64 ] <https://repo.mongodb.org/apt/ubuntu> focal/mongodb-org/6.0 multiverse" > /etc/apt/sources.list.d/mongodb-org-6.0.list
  - apt-get update -yqq
  - apt-get install -yqq --no-install-recommends build-essential

build-debug:
  stage: build
  script:
    - rustc --version && cargo --version
    - cargo build --bin knowmark-server --verbose
  artifacts:
    paths:
      - target/x86_64-unknown-linux-gnu/debug/knowmark-server
  cache:
    key:
      files:
        - Cargo.toml
    paths:
      - target

test-debug:
  stage: test
  needs:
    - build-debug
  variables:
    MONGODB_URI: mongodb
  script:
    - apt-get install -yqq --no-install-recommends gnupg mongodb-org
    - sudo systemctl start mongod
    - cargo test --workspace --verbose

build-linux:
  stage: build_targets
  needs:
    - test-debug
  script:
    - rustup target add x86_64-unknown-linux-gnu
    - cargo build --release --bin knowmark-server --target x86_64-unknown-linux-gnu --verbose
  artifacts:
    paths:
      - target/x86_64-unknown-linux-gnu/release/knowmark-server

build-windows:
  stage: build_targets
  needs:
    - test-debug
  script:
    - rustup target add x86_64-pc-windows-gnu
    - cargo build --release --bin knowmark-server --target x86_64-pc-windows-gnu --verbose
    - cargo build --release --bin knowmark-win-service --target x86_64-pc-windows-gnu --features windows-service --verbose
  artifacts:
    paths:
      - target/x86_64-pc-windows-gnu/release/knowmark-server.exe
      - target/x86_64-pc-windows-gnu/release/knowmark-win-service.exe

build-openbsd:
  stage: build_targets
  needs:
    - test-debug
  script:
    - rustup target add x86_64-unknown-openbsd
    - cargo build --release --bin knowmark-server --target x86_64-unknown-openbsd --verbose
  artifacts:
    paths:
      - target/x86_64-unknown-openbsd/release/knowmark-server

build-apple-x64:
  stage: build_targets
  needs:
    - test-debug
  script:
    - rustup target add x86_64-apple-darwin
    - cargo build --release --bin knowmark-server --target x86_64-apple-darwin --verbose
  artifacts:
    paths:
      - target/x86_64-apple-darwin/release/knowmark-server

build-apple-arm:
  stage: build_targets
  needs:
    - test-debug
  script:
    - rustup target add aarch64-apple-darwin
    - cargo build --release --bin knowmark-server --target aarch64-apple-darwin --verbose
  artifacts:
    paths:
      - target/aarch64-apple-darwin/release/knowmark-server
